name = "Demultiplex"
uuid = "65c8ffb1-ee6d-406d-bfb3-dd2ddae09be4"
authors = ["I.Mihara <issei.mihara@xforestx.com> and contributors"]
version = "1.0.1"

[deps]
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.7"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["Test"]
