name = "DemultiplexJulia"
uuid = "65c8ffb1-ee6d-406d-bfb3-dd2ddae09be4"
authors = ["I.Mihara <issei.mihara@xforestx.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
